/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const aggregate: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const anomalies: (a: number, b: number, c: number, d: number) => void;
export const binAssign: (a: number, b: number, c: number, d: number, e: number) => void;
export const binThresholds: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const binThresholdsInterval: (a: number, b: number, c: number, d: number) => void;
export const categoryOutliers: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => void;
export const changepoints: (a: number, b: number, c: number, d: number) => void;
export const combineCodes: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const counts: (a: number, b: number, c: number, d: number) => void;
export const cumsum: (a: number, b: number, c: number) => void;
export const decompose: (a: number, b: number, c: number, d: number) => void;
export const diff: (a: number, b: number, c: number) => void;
export const forecast: (a: number, b: number, c: number, d: number) => void;
export const frequencyOutliers: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const impute: (a: number, b: number, c: number, d: number, e: number) => void;
export const normalize: (a: number, b: number, c: number, d: number, e: number) => void;
export const pctChange: (a: number, b: number, c: number) => void;
export const quantileRank: (a: number, b: number, c: number) => void;
export const rank: (a: number, b: number, c: number) => void;
export const seasonality: (a: number, b: number, c: number, d: number) => void;
export const seriesOutliers: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const start: () => void;
export const ticks: (a: number, b: number, c: number, d: number) => void;
export const trend: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const version: (a: number) => void;
export const window: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_start: () => void;
